#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Use `python` or `python3`, based on availability
if command -v python3 >/dev/null 2>&1; then
  PYTHON_EXEC=python3
elif command -v python >/dev/null 2>&1; then
  PYTHON_EXEC=python
else
  echo "Python is not installed." >&2
  exit 1
fi

"$PYTHON_EXEC" .husky/validate-commit-msg.py "$1"
