#!/bin/bash

# Please don't push .husky files
if git diff --cached --name-only | grep '^.husky/'; then
  echo "You are trying to commit changes to the .husky directory."
  echo "This directory is not meant to be altered. Please unstage changes to the file."
  exit 1
fi

# Prevent commits to .github/ directory
if git diff --cached --name-only | grep -q '^.github/'; then
  echo "You are trying to commit changes to the .github directory."
  echo "This directory is not meant to be altered. Please unstage changes to the file."
  exit 1
fi

# Format and checkstyle
npm run format
npm run lint

# Run tests
# npx playwright test
